name: Deploy Next.js to Cloud Run

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v2

    # 设置 Node.js 环境
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.18.0'

    # 安装依赖
    - name: Install dependencies
      run: npm install

    # 构建 Next.js 应用
    - name: Build Next.js application
      run: npm run build

    # 构建 Docker 镜像
    - name: Build Docker image
      run: |
        docker build -t gcr.io/cs2060-spring-2024/content-moderation .
    
    # 配置 Google Cloud 凭据
    - name: Set up Google Cloud credentials
      uses: google-github-actions/setup-gcloud@v3
      with:
        project_id: cs2060-spring-2024
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    # 推送镜像到 Google Container Registry (GCR)
    - name: Push Docker image to GCR
      run: |
        docker tag gcr.io/cs2060-spring-2024/content-moderation gcr.io/cs2060-spring-2024/content-moderation:latest
        docker push gcr.io/cs2060-spring-2024/content-moderation:latest

    # 部署到 Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy content-moderation \
          --image gcr.io/cs2060-spring-2024/content-moderation:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
